nelmio_api_doc:
    documentation:
        servers:
          - url: http://localhost:8015
            description: API over HTTP
        info:
            title: Ecommerce Test Api
            description: Test Api definitions
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []

    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc)