version: '3'

services:
  db:
    container_name: acommerce-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: acommerce
      MYSQL_USER: acommerce
      MYSQL_PASSWORD: acommerce
      MYSQL_ROOT_PASSWORD: acommerce
    ports:
      - "33061:3306"
    networks:
      - acommerce

  app:
    container_name: acommerce-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - acommerce
  web:
    container_name: acommerce-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
          - ./:/var/www/html
    ports:
      - "8015:80"
    networks:
      - acommerce

networks:
    acommerce: